<h1>Scala map problems</h1>
<b>Note:</b> Please enter your problem solutions in the two cells immediately below this one. All other work should go below these two cells (and will be ignored by the graders!)

In [40]:
//PROBLEM 1 SOLUTION
val test_data = "widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2" 

//YOUR FUNCTION SHOULD GO HERE
def inventory_value(inventory: String) = 
    inventory.toLowerCase.split(",").
    map(i=>i.split(" ")).
    map(i=>(i(0),i(1))).
    sortWith(_._1 < _._1).
    groupBy(_._1).
    mapValues(i=>i.map(j=>j._2.toDouble).reduce(_+_))


//Test your function here
inventory_value(test_data)
//should return
//res1: scala.collection.immutable.Map[String,Double] = Map(eggs -> 345.22, milk -> 245.45, widgets -> 226.35)

test_data: String = widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2
inventory_value: (inventory: String)scala.collection.immutable.Map[String,Double]
res18: scala.collection.immutable.Map[String,Double] = Map(eggs -> 345.22, milk -> 245.45, widgets -> 226.35)


In [41]:
//PROBLEM 2 SOLUTION
val test_data = "able was i ere i saw elba, and that was before i was able and could see elba!"

//YOUR FUNCTION SHOULD GO HERE
def letter_count(sentence: String) = 
    sentence.toLowerCase.toCharArray.                    // convert the string to an Array of Characters
    filter(_.isLetter).                                  // filter out non-letter Characters
    map(i=>(i,1)).                                       // create tuples containing the (Char and 1)
    sortWith(_._1 < _._1).                               // sort tuples by Character
    groupBy(_._1).                                       // group by Character
    map(j => (j._1,j._2.map(_=>1).reduce(_+_)))          // map and reduce


//Test your function here
letter_count(test_data)
//Should return:
//scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3,
//                                               b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)

test_data: String = able was i ere i saw elba, and that was before i was able and could see elba!
letter_count: (sentence: String)scala.collection.immutable.Map[Char,Int]
res19: scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)


<h1>Scala Problem 1</h1>

Write a scala function "inventory_value" that takes a single argument, inventory, as an input and reports the total value of each item in the list. 

For example, if the inventory list is in the form:
"widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2” your function should output:

res58: scala.collection.immutable.Map[String,Double] = Map(eggs -> 345.22, milk -> 245.45, widgets -> 226.35)


You can assume that the string is well formed. I.e., there are no spaces other than the ones between the product name and the inventory value, that each item pair is separated by a comma, each item name is exactly one word, and each value is convertible into double without errors.

Helpful functions:

1. mapValues: m mapValues f applies f to the values of key,value pairs in m (you can
get this using a group by operation) 

2. sum: adds up numbers in a collection
Though you can use reduce for this, using mapValues and sum is a lot simpler

In [1]:
val test_data = "widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2" 

Intitializing Scala interpreter ...

Spark Web UI available at http://ziyangs-mbp.attlocal.net:4040
SparkContext available as 'sc' (version = 2.4.6, master = local[*], app id = local-1594790309871)
SparkSession available as 'spark'


test_data: String = widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2


In [3]:
val x = test_data.toLowerCase.split(",")     // split comma

x: Array[String] = Array(widgets 103.24, eggs 345.22, milk 231.25, widgets 123.11, milk 14.2)


In [4]:
val y = x.map(i=>i.split(" "))              // split space

y: Array[Array[String]] = Array(Array(widgets, 103.24), Array(eggs, 345.22), Array(milk, 231.25), Array(widgets, 123.11), Array(milk, 14.2))


In [5]:
val z = y.map(i=>(i(0),i(1)))               // create tuples

z: Array[(String, String)] = Array((widgets,103.24), (eggs,345.22), (milk,231.25), (widgets,123.11), (milk,14.2))


In [6]:
val a = z.sortWith(_._1 < _._1).groupBy(_._1)        // sort and group by

a: scala.collection.immutable.Map[String,Array[(String, String)]] = Map(eggs -> Array((eggs,345.22)), milk -> Array((milk,231.25), (milk,14.2)), widgets -> Array((widgets,103.24), (widgets,123.11)))


In [7]:
val b = a.mapValues(i=>i.map(j=>j._2.toDouble).reduce(_+_))         // reduce

b: scala.collection.immutable.Map[String,Double] = Map(eggs -> 345.22, milk -> 245.45, widgets -> 226.35)


In [8]:
// put it all together

def inventory_value(inventory: String) = 
    inventory.toLowerCase.split(",").
    map(i=>i.split(" ")).
    map(i=>(i(0),i(1))).
    sortWith(_._1 < _._1).
    groupBy(_._1).
    mapValues(i=>i.map(j=>j._2.toDouble).reduce(_+_))

inventory_value: (inventory: String)scala.collection.immutable.Map[String,Double]


In [9]:
inventory_value(test_data) //should return
//res1: scala.collection.immutable.Map[String,Double] = Map(eggs -> 345.22, milk -> 245.45, widgets -> 226.35)

res1: scala.collection.immutable.Map[String,Double] = Map(eggs -> 345.22, milk -> 245.45, widgets -> 226.35)


<h2>mapValues function</h2>

In [10]:
val d = Map('a' -> 12,'b'->15) // Creates a key --> value map
d.mapValues(i=>i*i) //Applies the function to the values of d 

d: scala.collection.immutable.Map[Char,Int] = Map(a -> 12, b -> 15)
res2: scala.collection.immutable.Map[Char,Int] = Map(a -> 144, b -> 225)


<h1>Scala problem 2</h1>
Write a scala function that <b>counts the number of each letter in a text string.</b> 

For example, if the input string is "able was i ere i saw elba, and that was before i was able and could see elba!”, your program should return:

Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)

Note that you should only count the letters and ignore all punctuation, numbers, spaces, or any special characters. 

The scala function isLetter returns true if a character is a letter and false otherwise.

In [11]:
val text = "able was i ere i saw elba, and that was before i was able and could see elba!"

text: String = able was i ere i saw elba, and that was before i was able and could see elba!


In [29]:
val aa = text.toLowerCase.toCharArray        // convert the string to an Array of Characters

aa: Array[Char] = Array(a, b, l, e,  , w, a, s,  , i,  , e, r, e,  , i,  , s, a, w,  , e, l, b, a, ,,  , a, n, d,  , t, h, a, t,  , w, a, s,  , b, e, f, o, r, e,  , i,  , w, a, s,  , a, b, l, e,  , a, n, d,  , c, o, u, l, d,  , s, e, e,  , e, l, b, a, !)


In [30]:
val bb = aa.filter(_.isLetter)               // filter out non-letter Characters

bb: Array[Char] = Array(a, b, l, e, w, a, s, i, e, r, e, i, s, a, w, e, l, b, a, a, n, d, t, h, a, t, w, a, s, b, e, f, o, r, e, i, w, a, s, a, b, l, e, a, n, d, c, o, u, l, d, s, e, e, e, l, b, a)


In [33]:
val cc = bb.map(i=>(i,1))                    // create tuples containing the (Char and 1)

cc: Array[(Char, Int)] = Array((a,1), (b,1), (l,1), (e,1), (w,1), (a,1), (s,1), (i,1), (e,1), (r,1), (e,1), (i,1), (s,1), (a,1), (w,1), (e,1), (l,1), (b,1), (a,1), (a,1), (n,1), (d,1), (t,1), (h,1), (a,1), (t,1), (w,1), (a,1), (s,1), (b,1), (e,1), (f,1), (o,1), (r,1), (e,1), (i,1), (w,1), (a,1), (s,1), (a,1), (b,1), (l,1), (e,1), (a,1), (n,1), (d,1), (c,1), (o,1), (u,1), (l,1), (d,1), (s,1), (e,1), (e,1), (e,1), (l,1), (b,1), (a,1))


In [35]:
val dd = cc.sortWith(_._1 < _._1).                         // sort tuples by Character
        groupBy(_._1).                                     // group by Character
        map(j => (j._1,j._2.map(_=>1).reduce(_+_)))        // map and reduce

dd: scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)


In [38]:
// put it all together

def letter_count(sentence: String) = 
    sentence.toLowerCase.toCharArray.                    // convert the string to an Array of Characters
    filter(_.isLetter).                                  // filter out non-letter Characters
    map(i=>(i,1)).                                       // create tuples containing the (Char and 1)
    sortWith(_._1 < _._1).                               // sort tuples by Character
    groupBy(_._1).                                       // group by Character
    map(j => (j._1,j._2.map(_=>1).reduce(_+_)))          // map and reduce

letter_count: (sentence: String)scala.collection.immutable.Map[Char,Int]


In [39]:
letter_count(text)
//Should return:
//scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3,
//                                               b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)

res17: scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)


<h2>isLetter</h2>
<li>returns true if a character is a letter of the alphabet and false otherwise

In [13]:
'p'.isLetter

res4: Boolean = true


In [14]:
'2'.isLetter

res5: Boolean = false


In [15]:
'?'.isLetter

res6: Boolean = false
